POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "Fazedo um CRUD com NestJS e Prisma",
  "content": "Aprenda a fazer um CRUD automático com NestJS e Prisma",
  "published": true,
  "authorId": 1
}
